jobs:
  build:
    docker:
      - image: cimg/php:8.0.14-browsers
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    working_directory: ~/laravel9_vue3_sancum_auth # directory where steps will run	  
    steps:
      - checkout
      - run: php --version 
  test:
    docker:
      - image: cimg/php:8.0.14-browsers
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run: composer global require tightenco/tlint
      - run: tlint
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test	  